[package]
name = "tpt-l-apt-keyring"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "OpenPGP keyring management and Release file verification for APT"
keywords = ["apt", "gpg", "pgp", "debian", "security"]
categories = ["cryptography", "authentication"]

[dependencies]
thiserror = { workspace = true }
tracing = { workspace = true }
pgp = { workspace = true }
hex = { workspace = true }
chrono = "0.4"

[dev-dependencies]
rand = "0.8"
smallvec = "1"
tempfile = { workspace = true }
