[package]
name = "tpt-l-dpkg-db"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "README.md"
description = "Concurrent reader/writer for the dpkg package status database"
keywords = ["debian", "dpkg", "database", "packages", "apt"]
categories = ["filesystem", "data-structures"]

[dependencies]
tpt-l-control-file = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
memmap2 = { workspace = true }
